# Disallowing packages: openvpn
# If you require these packages, please review the package approval process at: https://github.com/travis-ci/apt-package-whitelist#package-approval-process
#addons:
#    apt:
#        sources:
#            - ubuntu-toolchain-r-test
#        packages:
#            - openvpn

services:
    - docker

before_install:
    - docker --version

install:
    - git clone https://github.com/docker-library/official-images.git official-images

# Assist with ci test debugging:
#   - DEBUG=1
before_script:
    - image="kylemanna/openvpn"
    - docker build -t "$image" .
    - docker inspect "$image"
    - docker run --rm "$image" openvpn --version || true # why does it return 1?
    - docker run --rm "$image" openssl version

script:
    - official-images/test/run.sh "$image"
    - test/run.sh "$image"

after_script:
    - docker images
