name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_IMAGE: atymchuk/openvpn

    steps:
      #   - uses: actions/checkout@v3

      # - name: Build a x86_64 image
      #   run: |
      #     echo "Building image..."
      #     docker build -t "$DOCKER_IMAGE" .
      #     docker inspect "$DOCKER_IMAGE"
      #     docker run --rm "$DOCKER_IMAGE" openvpn --version
      #     docker run --rm "$DOCKER_IMAGE" openssl version

      - name: Run tests
        run: |
          echo "Running tests..."
          test/run.sh "$DOCKER_IMAGE"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push to Docker Hub
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: "{{ env.DOCKER_IMAGE }}:latest"

      - name: Print software versions
        run: |
          docker inspect "$DOCKER_IMAGE"
          docker run --rm "$DOCKER_IMAGE" openvpn --version
          docker run --rm "$DOCKER_IMAGE" openssl version
